---
  - name: creating MySQL Server docker image
    docker_image:
      path: /vagrant/provisioning/roles/mysql/files
      name: mysql
    register: mysqlcreated

  - name: starting MySQL container
    when: mysqlcreated|success
    docker_container:
      name: mysqld
      image: mysql
      state: started
      ports:
        - "{{ mysql_port }}:{{ mysql_port }}"
      networks:
        - name: "{{ network }}"
          ipv4_address: "{{ mysql_ip }}"
