---
  - name: creating Consul Server docker image
    docker_image:
      path: /vagrant/provisioning/roles/consul/files
      name: consul
    register: consulcreated

  - name: starting Consul container
    when: consulcreated|success
    docker_container:
      name: consuld
      image: consul
      state: started
      ports:
        - "{{ consul_port }}:{{ consul_port }}"
      networks:
        - name: "{{ network  }}"
          ipv4_address: "{{ consul_ip }}"
